<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGxx2c3p\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGxx2c3p/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGxx2c3p.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGxx2c3p\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGxx2c3p\appProdProjectContainer(array(
    'container.build_hash' => 'Gxx2c3p',
    'container.build_id' => '4d9cfe5b',
    'container.build_time' => 1545396757,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGxx2c3p');
